version: "3.9"

services:
  db:
    image: postgres:15
    container_name: cybersec-db
    restart: always
    environment:
      POSTGRES_DB: cybersec_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: cybersec-app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://user:password@db:5432/cybersec_db
    volumes:
      - .:/app

  alembic:
    build:
      context: .
    container_name: cybersec-alembic
    depends_on:
      - db
    command: alembic upgrade head
    environment:
      DATABASE_URL: postgresql+psycopg://user:password@db:5432/cybersec_db
    volumes:
      - .:/app

volumes:
  postgres_data:
