services:
  db:
    image: postgres:15
    container_name: cybersec-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: cybersec-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki/rules/fake:/loki/rules/fake
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki_data:/loki

  promtail:
    image: grafana/promtail
    volumes:
      - ./promtail:/etc/promtail
      - /etc/machine-id:/etc/machine-id:ro 
      - /var/log/journal:/var/log/journal:ro
    command: -config.file=/etc/promtail/promtail-config.yaml -config.expand-env=true
    environment:
    - HOST_IP=localhost
    - SOURCE_TYPE=server
    - USER=pao
    user: root

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data:
  loki_data:
