services:
  db:
    image: postgres:15
    container_name: cybersec-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: cybersec-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app

  alembic:
    build:
      context: .
    container_name: cybersec-alembic
    depends_on:
      - db
    command: uv run alembic upgrade head
    env_file:
      - .env

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'

volumes:
  postgres_data:
