groups:
  - name: config-change
    rules:
      - alert: SuspiciousConfigChanges
        expr: 'count_over_time({job="systemd"} |= "sudo" or "visudo" [1m]) > 2'
        for: 1m
        labels:
          severity: Высокий
          category: Изменение конфигурации
          source_type: server
        annotations:
          summary: "Обнаружены подозрительные изменения конфигурации"
